# Generated by Django 2.2.1 on 2019-06-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('designation', models.CharField(max_length=40)),
                ('salary', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveConverseResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileConverseResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('balance', models.IntegerField()),
                ('days', models.IntegerField()),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('reason', models.CharField(max_length=150)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
