# Generated by Django 2.2.1 on 2019-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='days',
            field=models.IntegerField(),
        ),
    ]
