# Generated by Django 2.2.1 on 2019-05-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190525_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveConverseResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=400)),
            ],
        ),
    ]
