# Generated by Django 2.2.1 on 2019-06-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_profileconverseresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='from_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='leave',
            name='to_date',
            field=models.DateField(default=None),
        ),
    ]
