# Generated by Django 2.2.1 on 2019-06-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20190625_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='from_date',
            new_name='fromdate',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='to_date',
            new_name='todate',
        ),
    ]
